version: '3'
services:
  db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  redis-server:
    image: 'redis'
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: intrasudo-node-app
    env_file: ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    stdin_open: true
    tty: true

volumes:
  db-config:
  db-data:
